spring.application.name=ordering-service

# PostgreSQL for Inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# MongoDB for Orders
spring.mongodb.uri=mongodb://localhost:27017/shop-order

# Enable Eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# RabbitMQ
rabbitmq.queue.name=shop_queue

# Payment Client
payment.client.url=http://localhost:8081