spring.application.name=orderingservice
server.port=8084

# PostgreSQL for Inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB for Orders
spring.mongodb.uri=mongodb://localhost:27017/shop-order
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Enable Eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Payment Client
payment.client.url=http://PAYMENTSERVICE

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/realms/shop-realm

# RabbitMQ

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Custom queue/exchange names
rabbitmq.exchange.name=shop_exchange
rabbitmq.routing.key=shop_routing_key
rabbitmq.queue.name=shop_queue

payment.request.queue=
payment.response.queue=
payment.exchange.key=
payment.request.routing.key=
payment.result.routing.key=
