spring.application.name=ordering-service
server.port=8084

# PostgreSQL for Inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB for Orders
spring.mongodb.uri=mongodb://localhost:27017/shop-order
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Enable Eureka Client
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Security
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/realms/shop-realm

# RabbitMQ Connection
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Enable RabbitMQ listener retries
spring.rabbitmq.listener.simple.retry.enabled=true

# Initial wait time between retries (1 second)
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms

# Maximum number of retry attempts before rejecting the message
spring.rabbitmq.listener.simple.retry.max-retries=3

# Wait time multiplier (1s -> 2s -> 4s)
spring.rabbitmq.listener.simple.retry.multiplier=2.0


# RabbitMQ Queues & Keys
rabbitmq.exchange.name=shop_exchange
rabbitmq.routing.key=shop_routing_key
rabbitmq.queue.name=shop_queue

payment.exchange.key=shop_exchange
payment.request.queue=payment_request_queue
payment.response.queue=payment_result_queue
payment.request.routing.key=payment.request.key
payment.result.routing.key=payment.result.key