spring.application.name=messageservice

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


rabbitmq.queue.name=shop_queue
rabbitmq.exchange.name=shop_exchange
rabbitmq.routing.key=shop_key