# --- Server & Application ---
server.port=8080
spring.application.name=apigatewayservice

# --- Eureka Discovery Client ---
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- Spring Cloud Gateway (WebFlux) ---
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route 1: Ordering Service
spring.cloud.gateway.routes[0].id=orderingservice
spring.cloud.gateway.routes[0].uri=lb://ORDERINGSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/order/**

# Route 2: Payment Service
spring.cloud.gateway.routes[1].id=paymentservice
spring.cloud.gateway.routes[1].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/payment/**

# Route 3: Food Service
spring.cloud.gateway.routes[2].id=foodservice
spring.cloud.gateway.routes[2].uri=lb://FOODSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/foods/**

# Auth Service Route
spring.cloud.gateway.routes[3].id=authservice
spring.cloud.gateway.routes[3].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

# --- Custom Security (CORS) ---
app.security.cors.allowed-origins[0]=http://localhost:5173

app.security.cors.max-age=3000

# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/realms/shop-realm

# Add this line (Must match the exact string in authservice's JwtUtil.java):
jwt.secret=R7MIxXagihMkD2VLHTP7GQVY795i2D2CcdGCIYW+cow=