# --- Server & Application ---
server.port=8080
spring.application.name=api-gateway

# --- Eureka Discovery Client ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- Spring Cloud Gateway (WebFlux) ---
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route 1: Ordering Service
spring.cloud.gateway.server.webflux.routes[0].id=ordering-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDERING-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/order/**

# Route 2: Payment Service
spring.cloud.gateway.server.webflux.routes[1].id=payment-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/payment/**

# --- Custom Security (CORS) ---
app.security.cors.allowed-origins[0]=http://localhost:5173
app.security.cors.max-age=3000