syntax = "proto3";

package paymentservice;

// This tells Protobuf where to generate the Java classes
option java_package = "com.shop.paymentservice.protobuf";
// This generates a separate Java file for each message, keeping your code clean
option java_multiple_files = true;

message PaymentRequestProto {
  string order_id = 1;
  string customer_id = 2;
  string amount = 3;
  string payment_mode = 4;
}

message PaymentResponseProto {
  string order_id = 1;
  string transaction_id = 2;
  bool success = 3;
  string message = 4;
}