spring.application.name=foodservice
server.port=8089
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Automatically create/update the tables based on your Java Models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Redis Caching Configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Optional: Set a Time-To-Live (TTL) for the cache so it refreshes automatically (e.g., 1 hour)
spring.cache.redis.time-to-live=36000000