spring.application.name=authservice
server.port=8989

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# PostgreSQL for Inventory
spring.datasource.url=jdbc:postgresql://shop-postgres:5432/shop_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

hmac.sha.key=${JWT_SECRET}
jwt.session.expiry=3600000
