spring.application.name=authservice
server.port=8989


# PostgreSQL for Inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

hmac.sha.key=1234
jwt.session.expiry=1234