spring.application.name=paymentservice

# Set a dedicated port to avoid collisions with port 8080
server.port=8082

# --- Eureka Client Configuration ---
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# --- PostgreSQL Configuration ---
# Make sure shop_db (or payment_db) exists in your local PostgreSQL!
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Razorpay Credentials ---
# Replace these with your actual test keys from the Razorpay Dashboard when ready
razorpay.api.key=rzp_test_yourKeyHere
razorpay.api.secret=yourSecretHere
razorpay.webhook.secret=my_super_secure_webhook_secret_123

# --- Logging Configuration ---
logging.level.root=INFO
logging.level.com.shop.paymentservice=DEBUG

# SQL Logging (For Spring Boot 3+ / Hibernate 6+)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log File Output
logging.file.name=logs/paymentservice.log

# --- Redis Configuration ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- RabbitMQ Connection ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Queues & Keys 
payment.exchange.key=shop_exchange
payment.request.queue=payment_request_queue
payment.response.queue=payment_result_queue
payment.request.routing.key=payment.request.key
payment.result.routing.key=payment.result.key

# Dead Letter Queue config
rabbitmq.dlx.name=shop_dlx
rabbitmq.dlq.name=shop_dlq
rabbitmq.dlq.routing.key=shop.dlq.routing.key

# Enable RabbitMQ listener retries
spring.rabbitmq.listener.simple.retry.enabled=true

# Initial wait time between retries (1 second)
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms

# Maximum number of retry attempts before rejecting the message
spring.rabbitmq.listener.simple.retry.max-retries=3

# Wait time multiplier (1s -> 2s -> 4s)
spring.rabbitmq.listener.simple.retry.multiplier=2.0