spring.application.name=paymentservice

razorpay.api.key=rzp_test_yourKeyHere
razorpay.api.secret=yourSecretHere
razorpay.webhook.secret=my_super_secure_webhook_secret_123

# Set the default logging level for the whole application
logging.level.root=INFO

# Set a specific logging level for YOUR code
# DEBUG is great for development to see detailed flow
logging.level.com.shop.paymentservice=DEBUG

# See Hibernate SQL queries and parameters in the console
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Spring Boot will automatically create this file and write all logs to it
logging.file.name=logs/paymentservice.log

# --- Redis Configuration ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
